### ISSUE TITLE
Geiger counter loud af - option to set volume

### ISSUE THREAD

**Issue by elieven** [aidenybai/react-scan#109]
It would be great to be able to control the volume of the geiger counter as currently it nearly blows out my speakers.

**Comment by pivanov** [comment]
#133 Add support to configure volume via localStorage with the key react-scan-volume and a value between 0 and 1. We hope to add this as an option to the scan UI soon.

**Comment by elieven** [comment]
How about in the options you pass to `scan()`? That might be easier / quicker to add and would totally do. No need to design or implement any UI.
