### ISSUE TITLE
Google Maps becomes blank and unusable when `react-scan` Chrome Extension is enabled

### ISSUE THREAD

**Issue by NuclEnergy** [aidenybai/react-scan#117]
### Description

When the `react-scan` Chrome Extension is enabled, Google Maps turns into a blank white screen and becomes completely unusable.

#### Key Details

1. Google Maps is **not built with React**, yet `react-scan` seems to interfere with its normal rendering.
2. Disabling the `react-scan` extension resolves the issue, and Google Maps works as expected.

---

### Steps to Reproduce

1. Install the `react-scan` Chrome Extension.
2. Visit [Google Maps](https://maps.google.com).
3. Observe the rendering behavior: the map becomes a blank white screen and is non-functional.

---

### Expected Behavior

Google Maps should render and operate normally, even with the `react-scan` Chrome Extension enabled.

---

### Actual Behavior

The Google Maps page turns completely white and is unusable.

---

### Environment

- **Operating System**: macOS 15.2
- **Browser**: Google Chrome version 131.0.6778.140
- **`react-scan` Extension Version**: v1.0.0

---

### Possible Cause

`react-scan` may be interacting with the DOM in a way that breaks rendering on pages not using React, such as Google Maps.

---

### Suggestions

1. Add a compatibility check to avoid interfering with pages that do not contain React elements.

---

### Additional Screenshots

<img width="2428" alt="Screenshot 2024-12-13 at 16 51 48" src="https://github.com/user-attachments/assets/6f10ced6-e459-4d7d-bb25-7dd1c915c6f0" />

---

### Impact

This issue affects usability for users who rely on Google Maps while using the `react-scan` extension.

Please investigate and fix this compatibility issue to improve the stability and user experience of the `react-scan` extension.  
Thank you!

**Comment by zkMake** [comment]
I can also confirm this happening.

**Comment by pivanov** [comment]
Hey @NuclEnergy  and @zkMake :)
Thanks for the feedback we really appreciate it!

We just push [new version](https://github.com/aidenybai/react-scan/tree/main/packages/extension/build) of the react-scan extension. Can you check and confirm it's working fine now?

**Comment by NuclEnergy** [comment]
> Hey @NuclEnergy and @zkMake :) Thanks for the feedback we really appreciate it!
> 
> We just push [new version](https://github.com/aidenybai/react-scan/tree/main/packages/extension/build) of the react-scan extension. Can you check and confirm it's working fine now?

Google Maps is now running normally and the error no longer occurs, thanks for the fix!

**Comment by pivanov** [comment]
Nice :) Thank you guys!
