### ISSUE TITLE
extension: icon animation causing lag in extensions menu

### ISSUE THREAD

**Issue by KoenLemmen** [aidenybai/react-scan#121]
When I have react scanner on I cannot open my extensions menu in chrome without it lagging a lot, basically freezing the menu.
My guess is that its the icon updating very frequently. 
I included a video so the steps can be followed to replicate. 
There is a fair chance its just my browser, because I run a lot of extensions. 

https://github.com/user-attachments/assets/086a2b39-0f0f-40d1-9775-25bc63e68132

**Comment by aidenybai** [comment]
should be fixed in the latest version @KoenLemmen
