### ISSUE TITLE
README is unclear why is this better than React Developer Tools render highlighter

### ISSUE THREAD

**Issue by yairEO** [aidenybai/react-scan#13]
Hi!

There is a "video" in the REAMDE showcasing components are highlighted when re-rendered but how is that different from long-time React extension? People need to know in what ways is this different?

This is begging for a comparison.. 

<img  alt="image" src="https://github.com/user-attachments/assets/e5164eaf-b410-48ae-a448-0ce043df10ef">

**Comment by aidenybai** [comment]
i wrote some general motivations on why this package exists: https://x.com/aidenybai/status/1857122670929969551?s=46&t=Ls1rF7VDXKwFMhFJuI9tbA

i'll codify a comparison in the readme sometime tonight

**Comment by aidenybai** [comment]
added a bit of context!
