### ISSUE TITLE
great work! as a VUE user I would love to have such a tool!

### ISSUE THREAD

**Issue by 2eha0** [aidenybai/react-scan#14]

**Comment by reslear** [comment]
@aidenybai  Are there any plans to try to make one for vue or fr agnostic ?

that would be cool and historic )

**Comment by elonehoo** [comment]
i wrote one today, i am not sure if it has the same function as the current scan, but i want to finish it.

https://github.com/elonehoo/vue-scan

**Comment by reslear** [comment]
@elonehoo sounds cool, could you publish a demo?

**Comment by elonehoo** [comment]
yeah, but it it ugly now
