### ISSUE TITLE
React Developer Tools Not Working with React Scan Extension

### ISSUE THREAD

**Issue by NuclEnergy** [aidenybai/react-scan#161]
# Issue: React Developer Tools Not Working with React Scan Plugin

## Description

When using the React Scan plugin, React Developer Tools fails to work properly. Specifically, React Developer Tools cannot detect React applications, and the following error appears in the browser console:
<img width="518" alt="Screenshot 2024-12-23 at 12 10 01" src="https://github.com/user-attachments/assets/c1ff3e16-2200-4700-8a8b-44a257014b10" />

React Developer Tools also displays a message indicating that the page does not appear to be using React.

## Steps to Reproduce

1. Install and enable the React Scan plugin.
2. Open a page using React (e.g., [https://react.dev](https://react.dev)).
3. Check the React Developer Tools functionality.
4. Observe the error in the console and the inability of React Developer Tools to detect React.

## Expected Behavior

React Developer Tools and the React Scan plugin should work together without interfering with each other.

## Actual Behavior

When the React Scan plugin is enabled:

- React Developer Tools cannot detect React applications.
- The above error appears in the browser console.

## Environment

- **Browser**: Google Chrome Version 131.0.6778.205
- **Operating System**: macOS 15.2
- **React Developer Tools Version**: 6.0.1 (10/15/2024)
- **React Scan Version**: v1.0.0 (12/23/2024)

## Attachments

1. **Console Error Screenshot**:
   <img width="518" alt="Screenshot 2024-12-23 at 12 10 01" src="https://github.com/user-attachments/assets/c1ff3e16-2200-4700-8a8b-44a257014b10" />

2. **Page Screenshot**:
   <img width="1381" alt="Screenshot 2024-12-23 at 12 07 50" src="https://github.com/user-attachments/assets/20145abd-abca-40e6-ae6a-e50320aa800e" />

## Additional Information

- Tested in incognito mode with only React Developer Tools and React Scan enabled, but the issue persists.
- Both the browser and extensions are updated to their latest versions.

Thank you for investigating and looking into this issue!

**Comment by RobPruzan** [comment]
thanks for the well documented issue, will check it out and get it fixed

**Comment by yohnz** [comment]
use like this:
```
if (REACT_SCAN) {
    const { scan } = require('react-scan');
    scan({
        enabled: true
    });
}

import React, { Component } from 'react';
```

**Comment by pivanov** [comment]
Hey @NuclEnergy can you check with this one?
[chrome-extension.zip](https://github.com/user-attachments/files/18246858/chrome-extension.zip)

**Comment by NuclEnergy** [comment]
> Hey @NuclEnergy can you check with this one? [chrome-extension.zip](https://github.com/user-attachments/files/18246858/chrome-extension.zip)

Yes, now it works fine.

**Comment by pivanov** [comment]
Thank you! :) 
I will close this one!
