### ISSUE TITLE
Configure slow renders

### ISSUE THREAD

**Issue by cosmith** [aidenybai/react-scan#20]
Hi, I tried this package on our app and it works great! Thanks. 

Unfortunately we have a lot of components that trigger the logging. 

Am I right in my understanding that every render that shows up in a blue box is slower than a given threshold and those that are in a red box are in slower than the configurable `longTaskThreshold`?

If yes I'd like to focus on the worst offenders first so it would be helpful to configure the threshold for the blue boxes. I'd like to enable react-scan by default on every dev build so we can improve them as we develop new features, and gradually lower the threshold.

If not (every render is a blue box?) then maybe we can add this to the docs?

**Comment by aidenybai** [comment]
@cosmith awesome! Would you like to spin up a PR?

**Comment by cosmith** [comment]
Ok so I looked at the code and it seems like I should update it here?

https://github.com/aidenybai/react-scan/blob/a1af92e0ecad351ee561e61fe9b2724f7c2dbc05/src/core/web/perf-observer.ts#L14-L15

Would `taskThreshold` be a good name for this option? To have `taskThreshold` and `longTaskThreshold`?

**Comment by cosmith** [comment]
So after digging a bit in the code, I think the blue boxes are displayed on every render, correct? So I guess we could add an option like `onlyShowSlowRenders`?

**Comment by cosmith** [comment]
I'm not sure what the best way to do this would be. 

I managed to get it to work by plugging inside `paintOutline` here 

https://github.com/cosmith/react-scan/blob/a1af92e0ecad351ee561e61fe9b2724f7c2dbc05/src/core/web/outline.ts#L227

But I have to recompute the duration by summing the render times, which is already done in `recalcOutlineColor`.

```
    if (options.onlyShowSlowRenders) {
      const { longTaskThreshold } = options;
      const minDuration = longTaskThreshold ?? 50;
      const maxDuration = Math.max(
        ...outline.renders.map((render) => render.time),
      );
      if (maxDuration < minDuration) {
        resolve();
        return;
      }
    }
```

I could also update `recalcOutlineColor` to return transparent or null and avoid drawing it in `fadeOutOutline`.

What do you think?

**Comment by aidenybai** [comment]
@cosmith hey so sorry i missed this - i wrote a `renderCountThreshold: number` option, you can use that!

**Comment by cosmith** [comment]
👍  Perfect thanks!
