### ISSUE TITLE
Cannot read properties of null (reading 'appendChild')

### ISSUE THREAD

**Issue by tencyle-nativs** [aidenybai/react-scan#36]
Getting this error - 
![image](https://github.com/user-attachments/assets/e8d25625-e2aa-42f5-ba5d-a7d49d20eb8f)

Added the script tag in my index.html file. I am using vite react over typescriprt -
![image](https://github.com/user-attachments/assets/2601e735-48a9-4672-8988-d2723c6f26d4)

**Comment by claritypotion** [comment]
`https://unpkg.com/react-scan@0.0.25/dist/auto.global.js`

25 seems to work, 26+ produces the error above

**Comment by aidenybai** [comment]
@claritypotion @tencyle-nativs can you try latest (0.0.30)?

**Comment by tencyle-nativs** [comment]
> @claritypotion @tencyle-nativs can you try latest (0.0.30)?

Yes its working, thanks :)
