### ISSUE TITLE
Scrollbar issue

### ISSUE THREAD

**Issue by alexandre-tobia** [aidenybai/react-scan#41]
Hello,

When installing react-scan in my project it get rid of my scrollbar on my table (actually there are just not perceptible)

Before : 
![Capture d’écran 2024-11-26 à 10 37 00](https://github.com/user-attachments/assets/72d7b617-c859-463e-8f2d-766851d9e3c0)

After:
![Capture d’écran 2024-11-26 à 10 39 22](https://github.com/user-attachments/assets/382a7097-97b5-4b00-b262-d71df50de32c)

It looks like react scan add theses styles : 
![Capture d’écran 2024-11-26 à 10 37 38](https://github.com/user-attachments/assets/17ccfe78-2d80-41cd-a620-973bc565e71d)

Could you make thoses to only target your code ?  and not make it globally (*)

Thanks a lot for your work :)

**Comment by alexgarabt** [comment]
I also been some time checking the styles on my project to see what it fails. I will try to make a pull request to fix the bug

**Comment by alexgarabt** [comment]
> I also been some time checking the styles on my project to see what it fails. I will try to make a pull request to fix the bug

I did make a [pull request](https://github.com/aidenybai/react-scan/pull/44) that fixes the bug. I hope they merge it.
