### ISSUE TITLE
How to initialize react-scan by exported API but not public CDN distributed script?

### ISSUE THREAD

**Issue by Asuka109** [aidenybai/react-scan#82]
I am trying to integrate react-scan into my private web applications. However, I am unable to access the public distributed script https://unpkg.com/react-scan/dist/auto.global.js from our internal network.

I would like to know if react-scan plans to maintain backward compatibility so that I can deploy the auto.global.js script to our own CDN. Or should I manage different versions of auto.global.js using a URL prefix?

Alternatively, is there a way to initialize react-scan using the APIs exported by the npm package? It seems that [auto.ts](https://github.com/aidenybai/react-scan/blob/main/packages/scan/src/auto.ts#L1) imports side effects from core/instrumentation/init.ts to initialize the React DevTools context. Can I simply import it before importing React, rather than injecting auto.global.js?

**Comment by pivanov** [comment]
Actualy this one:
https://unpkg.com/react-scan/dist/auto.global.js 

redirects to:
https://unpkg.com/react-scan@0.0.42/dist/auto.global.js

So you can use directly this format to load any version (please have in mind that some old versions can have issues)


About the initialization ... `injecting is a tricky part :)` it's not that simple ... I will spend some time when I have some ... to make the browser extension to work with custom CDNs or internal networks.  Till then ... you can host the react-scan internally by serving `./packages/scan/dist/` in your private network and have a domain ... so here are few steps:

1. clone the repo
2. cd react-scan
3. pnpm install
4. pnpm build
5. serve it (prefer over https)

Hope this helps :)

**Comment by Asuka109** [comment]
I was thought that I can just bundle react-scan into my application by importing the package. But I realize it might break react-scan while the application have its configuration doesn't works with react-scan. So I will try your approach to inject a compiled script into html page. If everything goes well, I would like to contribute a documentation PR about integrating with a local auto.global.js file.

**Comment by Asuka109** [comment]
I think I had misunderstood it. I read the readme again and I am using the scan exported from react-scan. It can work without an injected script. I set up react-scan using the EntryPlugin of webpack, which can ensure react-scan is imported before any React runtime (like react-refresh). I believe it can maintain good compatibility while react-scan makes any modifications in the future.

**webpack.config.js**

```js
import path from 'path';
import webpack from 'webpack';

/** @type {import('webpack').Configuration} */
export default {
  plugins: [
    new webpack.EntryPlugin(
      import.meta.dirname,
      path.resolve(import.meta.dirname, 'src/bootstrap.ts'),
      { name: undefined }
    )
  ]
};
```

**src/bootstrap.ts**

```ts
import { scan } from 'react-scan'; // import this BEFORE react

if (typeof window !== 'undefined') {
  scan({
    enabled: true,
    log: true, // logs render info to console (default: false)
  });
}
```

**Comment by pivanov** [comment]
Yep this works!
If you can install the package in your private network everything should be ok, right?

**Comment by Asuka109** [comment]
Yep, I think so. Using an npm package synced from a public registry is much more maintainable than self deploying CDN assets.

**Comment by pivanov** [comment]
Yep :) 
I will close this one then! Thanks gaian!
