### ISSUE TITLE
Chrome extension maybe trying to load on iframes

### ISSUE THREAD

**Issue by leemr** [aidenybai/react-scan#87]
Have react-scan Chrome extension running.

- [ ] I expect not to see react-scan warning on Paypal sub-window.

When I opened a Paypal link, saw this.  Maybe the sub-window cannot display a layer on top.
<img width="569" alt="image" src="https://github.com/user-attachments/assets/b8371401-4c91-4f5b-b3d7-b9feab53e622">

I see this when I click the extension on the page above the Paypal link.
<img width="359" alt="image" src="https://github.com/user-attachments/assets/2736c2e4-eb35-4ad7-ac6a-e82ac15921de">

**Comment by aidenybai** [comment]
on it!
