### ISSUE TITLE
Is there any possible to make it a chrome extension?

### ISSUE THREAD

**Issue by arvinxx** [aidenybai/react-scan#9]
Thank you a lot! It's really cool and save my day! Really great job!

Can it be a chrome extension to auto enable when in dev mode?

**Comment by Gurvinder-Singh02** [comment]
I just had the Same thought

**Comment by li-changyu** [comment]
Really need it.

**Comment by davidgg** [comment]
Hey @NisargIO I've created a chrome extension. I know you're working on a solid and official extension. I'll take down mine when you publish the official. It requires the React Dev Tools enabled too to make it work for some sites. It's just a wrapper around the npm react-scan package: https://chromewebstore.google.com/detail/react-scan-toggle/jenlhondkkckfmehobgliecmdngfdkbo?authuser=0&hl=es

The code is available here: https://github.com/davidgg/react-scan-toggle-chrome

**Comment by davidgg** [comment]
> Hey @NisargIO I've created a chrome extension. I know you're working on a solid and official extension. I'll take down mine when you publish the official. It requires the React Dev Tools enabled too to make it work for some sites. It's just a wrapper around the npm react-scan package: https://chromewebstore.google.com/detail/react-scan-toggle/jenlhondkkckfmehobgliecmdngfdkbo?authuser=0&hl=es
> 
> The code is available here: https://github.com/davidgg/react-scan-toggle-chrome


pinging @aidenybai too

**Comment by pivanov** [comment]
I think we can close this one now.
[CHROME_EXTENSION_GUIDE.md](https://github.com/aidenybai/react-scan/blob/main/CHROME_EXTENSION_GUIDE.md)
